refactor: refactored each code

diff --git a/.github/workflows/taxi-booking-prod.yaml b/.github/workflows/taxi-booking-prod.yaml
--- a/.github/workflows/taxi-booking-prod.yaml
+++ b/.github/workflows/taxi-booking-prod.yaml
@@ -60,5 +60,5 @@ jobs:
           echo "Testing SSH connection..."
           ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "whoami" || { echo "SSH connection failed"; exit 1; }
           echo "Deploying to EC2..."
-          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "cd '$TARGET_DIR' && pwd && git fetch origin && git status && git pull origin trust-pay-stg --verbose && git log -1 --oneline && npm install && pm2 reload all --update-env" || { echo "Deployment failed"; exit 1; }
+          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "cd '$TARGET_DIR' && pwd && git fetch origin && git status && git pull origin taxi-booking-server --verbose && git log -1 --oneline && npm install && pm2 reload all --update-env" || { echo "Deployment failed"; exit 1; }
           rm -f private_key
